name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - 'ingametesting'
  pull_request:
    branches-ignore:
      - 'ingametesting'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper

    - name: Run Gradle
      run: ./gradlew clean build

    - name: Archive jar file
      uses: actions/upload-artifact@v3
      with:
        name: OldCombatMechanics
        path: build/libs/OldCombatMechanics.jar
